# main config file

# The following settings can be cleared safely.

[server]
    addr  = ""                                           # default is "0.0.0.0" or ipv4 "*"
    mux   = "gin"                                        # might be: iris, echo, gin, gorilla, default, ...
    port  = 9477
    ports = { tls = 9479, debug = 9478, default = 9477 }
    type  = ""                                           # http2 server always

[server.addresses]
    advertise = ""
    rpc       = ""

[server.auto-cert]
    domains           = ["example.com"]
    domains-2nd-level = ["api", "aurora", "home", "res"]
    enabled           = false

# used by certtool.XsTLSConfig
[server.tls.certs]
    # enabled = true
    ca-cert         = ""     # ca.pem (the implicit key file is ca.pem.key)
    cert            = ""     # cert.pem
    client-auth     = false  #
    key             = ""     # key.pem
    min-tls-version = 0x0304 # 0x0304 = v1.3, 0x0303 = v1.2, ...
    server-cert     = ""     # server.pem (another implicit file is server-bundle.pem)

[server.statics]
    assets    = { url = "/assets", path = "./static/assets" }
    templates = { path = "./static/templates", pattern = "*.tmpl", left = "{{", right = "}}" }
