baseURL      = "https://yourname.github.io/your-starter"
languageCode = "zh-CN"
title        = "Your-starter Docs"

# theme = 'hugo-theme-techdoc'
theme = 'hugo-book'

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage               = "en"
defaultContentLanguageInSubdir       = true
enableMissingTranslationPlaceholders = true

sectionPagesMenu = 'main'

# (Optional) Set this to true to enable Author.
enableGitInfo = true


# For hugo-book

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
# googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname = "my-site"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
# disableKinds = ['taxonomy', 'taxonomyTerm']
disableKinds = ['taxonomy']


# [module]
# [[module.imports]]
#     path = 'github.com/ntk148v/hugo-cuisine-book'

# [module]
# [[module.mounts]]
#     source = 'content'
#     target = 'content'
# [[module.mounts]]
#     source = '../d2.theme/themes/d2-theme'
#     target = 'themes/d2-theme'

[params]
    # Source Code repository section

    author      = "Your-starter Authors"
    description = "An funny tool"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

    # Date format
    # dateformat = "" # default "2 Jan 2006"
    dateformat = "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference


    # (Optional) Your logo in the header navbar which has to be stored in static folder.
    # If the logo is /static/logo.png then the path would be 'logo.png'
    # logo = "logo.png"

    # (Optional) Enable comments template on pages
    # By default partials/comments.html includes Disqus template
    # See https://gohugo.io/content-management/comments/#configure-disqus
    # Can be overwritten by same param in page frontmatter
    comment = true

    # Set source repository location.
    repo = "https://github.com/yourname/your-starter"

    # Enable 'Edit' links.
    # Disabled by default. Uncomment to enable. Requires 'repo' param.
    # Path must point to the site directory.
    editpath = 'edit/master/docs'

    # Enable 'Add' links.
    # Disabled by default. Uncomment to enable. Requires 'repo' param.
    # Path must point to the site directory.
    newpath = 'new/master/docs'

    BookTheme = 'dark'

    # (Optional, default true) Controls table of contents visibility on right side of pages.
    # Start and end levels can be controlled with markup.tableOfContents setting.
    # You can also specify this parameter per page in front matter.
    BookToC = true

    # (Optional, default favicon.png) Set the path to a favicon file.
    # If the favicon is /static/favicon.png then the path would be favicon.png
    # BookFavicon = 'favicon.png'

    # (Optional, default none) Set the path to a logo for the book.
    # If the logo is /static/logo.png then the path would be logo.png
    # BookLogo = 'logo.png'
    # BookLogo = 'images/og-image.png'

    # (Optional, default docs) Specify section of content to render as menu
    # You can also set value to "*" to render all sections to menu
    BookSection = '*' # 'Cmdr-CLI Docs'

    # Set source repository location.
    # Used for 'Last Modified' and 'Edit this page' links.
    BookRepo = 'https://github.com/your-name/your-starter'

    # Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
    # type.
    # Required if 'BookRepo' param is set.
    # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
    # Github uses 'commit', Bitbucket uses 'commits'
    BookCommitPath = 'commit'

    # Enable 'Edit this page' links for 'doc' page type.
    # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
    # Path must point to the site directory.
    BookEditPath = 'edit/master/docs'

    # (Optional, default January 2, 2006) Configure the date format used on the pages
    # - In git information
    # - In blog posts
    BookDateFormat = 'Jan 2, 2006'

    # (Optional, default true) Enables search function with flexsearch,
    # Index is built on fly, therefore it might slowdown your website.
    # Configuration for indexing can be adjusted in i18n folder per language.
    BookSearch = true

    # (Optional, default true) Enables comments template on pages
    # By default partials/docs/comments.html includes Disqus template
    # See https://gohugo.io/content-management/comments/#configure-disqus
    # Can be overwritten by same param in page frontmatter
    BookComments = true

    # /!\ This is an experimental feature, might be removed or changed at any time
    # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
    # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
    # Theme will print warning if page referenced in markdown does not exists.
    BookPortableLinks = true

    # /!\ This is an experimental feature, might be removed or changed at any time
    # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
    BookServiceWorker = true

    # /!\ This is an experimental feature, might be removed or changed at any time
    # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
    BookTranslatedOnly = false

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
    contentDir   = 'content'
    languageName = 'English'
    weight       = 1

[languages.zh]
    contentDir   = 'content.zh'
    languageName = 'Chinese'
    weight       = 2

    # [languages.he]
    #     contentDir        = 'content.he'
    #     languageDirection = 'rtl'
    #     languageName      = 'Hebrew'
    #     weight            = 3

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"

[markup.tableOfContents]
    endLevel   = 6
    ordered    = false
    startLevel = 1

# Needed for mermaid/katex shortcodes
[markup.goldmark.renderer]
    unsafe = true

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1

    # [[menu.main]]
    #     name   = "GitHub"
    #     url    = "https://github.com/yourname"
    #     weight = 2

# [[menu.before]]
[[menu.after]]
    name   = "Github"
    url    = "https://github.com/yourname/your-starter"
    weight = 10

    # [[menu.after]]
    #   name = "Hugo Themes"
    #   url = "https://themes.gohugo.io/themes/hugo-book/"
    #   weight = 20

[outputs]
    home = ["Algolia", "HTML", "RSS"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName       = "algolia"
    isPlainText    = true
    mediaType      = "application/json"
    notAlternative = true

[params.algolia]
    params = ["categories", "tags"]
    vars = [
        "content",
        "date",
        "description",
        "keywords",
        "lastmod",
        "permalink",
        "publishdate",
        "summary",
        "title",
    ]
